import { Product, Category, Banner, HomePageData } from '../models/types';

const PRODUCT_IMAGES = {
  turmeric: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400&q=80',
  ashwagandha: 'https://images.unsplash.com/photo-1509358740172-f77c168f6312?w=400&q=80',
  honey: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&q=80',
  ghee: 'https://images.unsplash.com/photo-1631209121750-a9f656e30702?w=400&q=80',
  tea: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&q=80',
  spices: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80',
  oil: 'https://images.unsplash.com/photo-1474979266404-7f28db3f3c9b?w=400&q=80',
  mortar: 'https://images.unsplash.com/photo-1492552296703-4ec0a2fb3715?w=400&q=80',
  herbs: 'https://images.unsplash.com/photo-1573505097552-7b205ec14e32?w=400&q=80',
  powder: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=400&q=80',
  seeds: 'https://images.unsplash.com/photo-1508747703725-719586714d47?w=400&q=80',
  nuts: 'https://images.unsplash.com/photo-1606890658317-7d14490b76fd?w=400&q=80',
};

export const mockCategories: Category[] = [
  { id: 1, name: 'Herbs & Spices', slug: 'herbs-spices', description: 'Pure natural herbs and spices', image: PRODUCT_IMAGES.spices, parent_id: 0, count: 24 },
  { id: 2, name: 'Ayurvedic', slug: 'ayurvedic', description: 'Traditional Ayurvedic preparations', image: PRODUCT_IMAGES.mortar, parent_id: 0, count: 18 },
  { id: 3, name: 'Honey & Ghee', slug: 'honey-ghee', description: 'Pure honey and desi ghee', image: PRODUCT_IMAGES.honey, parent_id: 0, count: 12 },
  { id: 4, name: 'Herbal Tea', slug: 'herbal-tea', description: 'Natural herbal teas', image: PRODUCT_IMAGES.tea, parent_id: 0, count: 15 },
  { id: 5, name: 'Oils', slug: 'oils', description: 'Cold-pressed natural oils', image: PRODUCT_IMAGES.oil, parent_id: 0, count: 10 },
  { id: 6, name: 'Seeds & Nuts', slug: 'seeds-nuts', description: 'Organic seeds and dry fruits', image: PRODUCT_IMAGES.nuts, parent_id: 0, count: 20 },
  { id: 7, name: 'Powders', slug: 'powders', description: 'Herbal and nutrient powders', image: PRODUCT_IMAGES.powder, parent_id: 0, count: 14 },
  { id: 8, name: 'Wellness', slug: 'wellness', description: 'General wellness products', image: PRODUCT_IMAGES.herbs, parent_id: 0, count: 16 },
];

export const mockProducts: Product[] = [
  {
    id: 1, name: 'Organic Turmeric Powder', slug: 'organic-turmeric-powder',
    description: 'Premium quality organic turmeric powder sourced from the farms of Erode, Tamil Nadu. Known for its high curcumin content and vibrant golden color. Traditionally used in Indian cuisine and wellness practices.',
    short_description: 'Pure organic turmeric powder with high curcumin content',
    price: '199', regular_price: '249', sale_price: '199', currency: 'INR',
    images: [{ id: 1, src: PRODUCT_IMAGES.turmeric, alt: 'Organic Turmeric Powder' }],
    category_ids: [1, 7], category_slugs: ['herbs-spices', 'powders'],
    stock_status: 'instock', average_rating: '4.5', rating_count: 128,
    attributes: [{ name: 'Weight', options: ['100g', '250g', '500g'] }, { name: 'Origin', options: ['Erode, Tamil Nadu'] }],
    related_products: [2, 5, 8],
  },
  {
    id: 2, name: 'Ashwagandha Root Powder', slug: 'ashwagandha-root-powder',
    description: 'Traditional Ashwagandha root powder prepared from sustainably harvested roots. A well-known adaptogenic herb in Ayurvedic tradition, used for centuries as a general tonic.',
    short_description: 'Premium Ashwagandha root powder - traditional adaptogenic herb',
    price: '349', regular_price: '449', sale_price: '349', currency: 'INR',
    images: [{ id: 2, src: PRODUCT_IMAGES.ashwagandha, alt: 'Ashwagandha Root Powder' }],
    category_ids: [2, 7], category_slugs: ['ayurvedic', 'powders'],
    stock_status: 'instock', average_rating: '4.7', rating_count: 256,
    attributes: [{ name: 'Weight', options: ['100g', '200g'] }, { name: 'Type', options: ['Root Powder'] }],
    related_products: [1, 3, 6],
  },
  {
    id: 3, name: 'Raw Forest Honey', slug: 'raw-forest-honey',
    description: 'Unprocessed raw honey collected from forest beehives. Rich in natural enzymes and nutrients. No added sugar, no artificial flavors. Pure and natural as sourced from nature.',
    short_description: 'Pure unprocessed raw forest honey - no added sugar',
    price: '499', regular_price: '599', sale_price: '499', currency: 'INR',
    images: [{ id: 3, src: PRODUCT_IMAGES.honey, alt: 'Raw Forest Honey' }],
    category_ids: [3], category_slugs: ['honey-ghee'],
    stock_status: 'instock', average_rating: '4.8', rating_count: 342,
    attributes: [{ name: 'Size', options: ['250ml', '500ml', '1L'] }],
    related_products: [4, 7],
  },
  {
    id: 4, name: 'A2 Desi Cow Ghee', slug: 'a2-desi-cow-ghee',
    description: 'Pure A2 desi cow ghee made using traditional bilona method. Rich in nutrients and prepared from grass-fed cow milk. Perfect for cooking and traditional wellness practices.',
    short_description: 'Traditional bilona method A2 desi cow ghee',
    price: '699', regular_price: '799', sale_price: '699', currency: 'INR',
    images: [{ id: 4, src: PRODUCT_IMAGES.ghee, alt: 'A2 Desi Cow Ghee' }],
    category_ids: [3], category_slugs: ['honey-ghee'],
    stock_status: 'instock', average_rating: '4.6', rating_count: 189,
    attributes: [{ name: 'Size', options: ['250ml', '500ml', '1L'] }],
    related_products: [3, 7],
  },
  {
    id: 5, name: 'Tulsi Green Tea', slug: 'tulsi-green-tea',
    description: 'A refreshing blend of green tea leaves and holy basil (Tulsi). This herbal tea is known for its soothing aroma and is traditionally consumed for overall wellness.',
    short_description: 'Refreshing blend of green tea and holy basil',
    price: '249', regular_price: '299', sale_price: '249', currency: 'INR',
    images: [{ id: 5, src: PRODUCT_IMAGES.tea, alt: 'Tulsi Green Tea' }],
    category_ids: [4], category_slugs: ['herbal-tea'],
    stock_status: 'instock', average_rating: '4.4', rating_count: 97,
    attributes: [{ name: 'Packs', options: ['25 bags', '50 bags', '100 bags'] }],
    related_products: [6, 1],
  },
  {
    id: 6, name: 'Chamomile Herbal Tea', slug: 'chamomile-herbal-tea',
    description: 'Calming chamomile herbal tea made from dried chamomile flowers. Known for its mild, pleasant flavor and relaxing properties. Caffeine-free and suitable for evening consumption.',
    short_description: 'Calming caffeine-free chamomile flower tea',
    price: '299', regular_price: '349', sale_price: '299', currency: 'INR',
    images: [{ id: 6, src: PRODUCT_IMAGES.tea, alt: 'Chamomile Herbal Tea' }],
    category_ids: [4], category_slugs: ['herbal-tea'],
    stock_status: 'instock', average_rating: '4.3', rating_count: 76,
    attributes: [{ name: 'Packs', options: ['20 bags', '40 bags'] }],
    related_products: [5, 8],
  },
  {
    id: 7, name: 'Cold Pressed Coconut Oil', slug: 'cold-pressed-coconut-oil',
    description: 'Pure cold-pressed virgin coconut oil extracted from fresh coconuts. Retains natural aroma and nutrients. Suitable for cooking, skin care, and hair care.',
    short_description: 'Pure virgin cold-pressed coconut oil',
    price: '399', regular_price: '499', sale_price: '399', currency: 'INR',
    images: [{ id: 7, src: PRODUCT_IMAGES.oil, alt: 'Cold Pressed Coconut Oil' }],
    category_ids: [5], category_slugs: ['oils'],
    stock_status: 'instock', average_rating: '4.5', rating_count: 204,
    attributes: [{ name: 'Size', options: ['200ml', '500ml', '1L'] }],
    related_products: [8, 4],
  },
  {
    id: 8, name: 'Triphala Churna', slug: 'triphala-churna',
    description: 'Traditional Triphala powder made from three fruits - Amla, Haritaki, and Bibhitaki. A time-honored Ayurvedic formulation used as a general wellness supplement.',
    short_description: 'Traditional Ayurvedic Triphala powder blend',
    price: '179', regular_price: '229', sale_price: '179', currency: 'INR',
    images: [{ id: 8, src: PRODUCT_IMAGES.powder, alt: 'Triphala Churna' }],
    category_ids: [2, 7], category_slugs: ['ayurvedic', 'powders'],
    stock_status: 'instock', average_rating: '4.6', rating_count: 167,
    attributes: [{ name: 'Weight', options: ['100g', '250g'] }],
    related_products: [2, 1],
  },
  {
    id: 9, name: 'Chia Seeds Premium', slug: 'chia-seeds-premium',
    description: 'Premium quality chia seeds rich in omega-3, fiber, and protein. These tiny seeds are packed with nutrients and can be added to smoothies, yogurt, or salads.',
    short_description: 'Nutrient-rich premium chia seeds',
    price: '299', regular_price: '399', sale_price: '299', currency: 'INR',
    images: [{ id: 9, src: PRODUCT_IMAGES.seeds, alt: 'Chia Seeds Premium' }],
    category_ids: [6], category_slugs: ['seeds-nuts'],
    stock_status: 'instock', average_rating: '4.4', rating_count: 134,
    attributes: [{ name: 'Weight', options: ['200g', '500g'] }],
    related_products: [10, 11],
  },
  {
    id: 10, name: 'Mixed Dry Fruits Pack', slug: 'mixed-dry-fruits',
    description: 'Premium assortment of almonds, cashews, raisins, and walnuts. Carefully selected and packed to retain freshness. Perfect as a healthy snack or gift.',
    short_description: 'Premium assorted dry fruits - almonds, cashews, raisins, walnuts',
    price: '599', regular_price: '749', sale_price: '599', currency: 'INR',
    images: [{ id: 10, src: PRODUCT_IMAGES.nuts, alt: 'Mixed Dry Fruits Pack' }],
    category_ids: [6], category_slugs: ['seeds-nuts'],
    stock_status: 'instock', average_rating: '4.7', rating_count: 289,
    attributes: [{ name: 'Weight', options: ['250g', '500g', '1kg'] }],
    related_products: [9, 11],
  },
  {
    id: 11, name: 'Moringa Leaf Powder', slug: 'moringa-leaf-powder',
    description: 'Pure moringa leaf powder from organically grown moringa trees. Known as a superfood, moringa is rich in vitamins, minerals, and antioxidants.',
    short_description: 'Organic moringa leaf powder - nutrient-rich superfood',
    price: '249', regular_price: '329', sale_price: '249', currency: 'INR',
    images: [{ id: 11, src: PRODUCT_IMAGES.herbs, alt: 'Moringa Leaf Powder' }],
    category_ids: [7, 8], category_slugs: ['powders', 'wellness'],
    stock_status: 'instock', average_rating: '4.3', rating_count: 98,
    attributes: [{ name: 'Weight', options: ['100g', '200g'] }],
    related_products: [1, 2, 8],
  },
  {
    id: 12, name: 'Kashmiri Saffron', slug: 'kashmiri-saffron',
    description: 'Authentic Kashmiri saffron (Kesar) threads. Premium grade with rich color and aroma. Traditionally used in cooking, beverages, and wellness preparations.',
    short_description: 'Premium authentic Kashmiri saffron threads',
    price: '899', regular_price: '1099', sale_price: '899', currency: 'INR',
    images: [{ id: 12, src: PRODUCT_IMAGES.spices, alt: 'Kashmiri Saffron' }],
    category_ids: [1], category_slugs: ['herbs-spices'],
    stock_status: 'instock', average_rating: '4.9', rating_count: 56,
    attributes: [{ name: 'Weight', options: ['1g', '2g', '5g'] }],
    related_products: [1, 5],
  },
];

export const mockBanners: Banner[] = [
  { id: 1, image: 'https://images.unsplash.com/photo-1573505097552-7b205ec14e32?w=800&q=80', title: 'Pure & Natural', subtitle: 'Discover Ayurvedic wellness products' },
  { id: 2, image: 'https://images.unsplash.com/photo-1635774855717-0aec182f92cc?w=800&q=80', title: 'Fresh Arrivals', subtitle: 'Organic herbs & spices collection' },
  { id: 3, image: 'https://images.unsplash.com/photo-1509358740172-f77c168f6312?w=800&q=80', title: 'Special Offers', subtitle: 'Up to 30% off on selected items' },
];

export const mockHomeData: HomePageData = {
  banners: mockBanners,
  categories: mockCategories,
  featured_products: mockProducts.slice(0, 6),
  new_arrivals: mockProducts.slice(6, 12),
  popular_products: [mockProducts[2], mockProducts[9], mockProducts[0], mockProducts[3], mockProducts[11], mockProducts[1]],
};
